[versions]
vaadin = "24.9.6"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.17"
# check jooq version at https://www.jooq.org/download/
jooq = "3.18.7"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaadin-boot = "com.github.mvysny.vaadin-boot:vaadin-boot:13.4"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
junit = "org.junit.jupiter:junit-jupiter-engine:6.0.1"
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v24:2.4.3"
karibu-dsl = "com.github.mvysny.karibudsl:karibu-dsl-v23:2.4.0"
flyway = "org.flywaydb:flyway-core:11.18.0"
h2 = "com.h2database:h2:2.2.224"
jooq-jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-meta = { module = "org.jooq:jooq-meta", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
# don't upgrade: https://github.com/http4k/http4k/issues/1454
http4k = "org.http4k:http4k-core:5.47.0.0"
gson-javatime = "com.fatboyindustrial.gson-javatime-serialisers:gson-javatime-serialisers:1.1.2"
hikaricp = "com.zaxxer:HikariCP:7.0.2"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
